# -*- coding: utf-8 -*-
#
# Logistic, Stock & MRP documentation build configuration file, created by
# sphinx-quickstart on Mon Mar  9 11:55:03 2009.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# The contents of this file are pickled, so don't put values in the namespace
# that aren't pickleable (module imports are okay, they're removed automatically).
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os
from docutils import nodes
sys.path.append('../../source')
from conf import *

TO_BE_DEFINED = None

master_doc = 'index'

# General information about the project.
project = TO_BE_DEFINED
copyright = TO_BE_DEFINED

version = '1.0'
release = '1.0'

# List of documents that shouldn't be included in the build.
unused_docs = [
]

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = [
]

# Options for HTML output
# -----------------------

# The style sheet to use for HTML and HTML Help pages. A file of that name
# must exist either in Sphinx' static/ path, or in one of the custom paths
# given in html_static_path.
html_style = 'default.css'

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = TO_BE_DEFINED

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

htmlhelp_basename = TO_BE_DEFINED


# Options for LaTeX output
# ------------------------

# The paper size ('letter' or 'a4').
#latex_paper_size = 'a4'

# The font size ('10pt', '11pt' or '12pt').
latex_font_size = '10pt'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, document class [howto/manual]).

latex_documents = [
  TO_BE_DEFINED
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = '.static/openerp.jpg'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
latex_use_parts = True
latex_show_pagerefs = True

# Additional stuff for the LaTeX preamble.
#latex_preamble = '' # DEPRECATED sinc sphinx 0.5 (use 'latex_elements')

formats = {
    'L156H234': {
        'width': '156mm',
        'height': '234mm',
        'notice_width': '79mm',
    },

    'L148H210': {
        'width': '148mm',
        'height': '210mm',
        'notice_width': '79mm',
    },
    'L189H246': {
        'width': '189mm',
        'height': '246mm',
        'notice_width': '105mm',
    },
}

#chosen_format = formats['L156H234']
chosen_format = formats['L189H246']

tiny_latex_include = r"""
\usepackage{flowfram}
\usepackage{multicol}
\usepackage[none]{hyphenat}
\usepackage[section]{placeins}

\usepackage[]{geometry}
\geometry{papersize={%(width)s,%(height)s},top=15mm,bottom=28mm,left=20mm,right=20mm,bindingoffset=5mm}

\usepackage{fancyhdr}

\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0.4pt}

\fancypagestyle{conclusion}{%%
  \fancyhf{} %% clear all header and footer fields
  \fancyfoot[LE,RO]{\bfseries \thepage}
  \fancyhead[RE,LO]{}
}

\fancypagestyle{foreword}{%%
  \fancyhf{} %% clear all header and footer fields
  \fancyfoot[LE,RO]{\bfseries \thepage}
  \fancyhead[RE,LO]{}
}

\fancypagestyle{main}{%%
  \fancyhf{} %% clear all header and footer fields
  \fancyfoot[RO]{\bfseries \leftmark\ \ \ \ \ \ \thepage}
  \fancyfoot[LE]{\bfseries \thepage\ \ \ \ \ \ \leftmark}
}

\renewcommand{\chaptermark}[1]{%%
  \markboth{\chaptername
  \ \thechapter.\ #1}{}}

\DeclareUnicodeCharacter{00A0}{~}

\hypersetup{
    colorlinks=true,
    linkcolor=black,
    citecolor=black,
    filecolor=black,
    urlcolor=black
}

\definecolor{TitleColor}{rgb}{0,0,0}
\definecolor{InnerLinkColor}{rgb}{0,0,0}
\definecolor{OuterLinkColor}{rgb}{0,0,0}
\definecolor{VerbatimColor}{rgb}{1,1,1}
\definecolor{VerbatimBorderColor}{rgb}{1,1,1}

\definecolor{NoticeBoxBg}{rgb}{0.95,0.95,0.95}

\newlength{\boxwidth}

\newenvironment{NoticeBox}{%%
  \def\FrameCommand{\fboxsep=\FrameSep \fboxrule=\FrameRule \fcolorbox{black}{NoticeBoxBg}}%%
  \MakeFramed {\setlength{\boxwidth}{\textwidth}
  \addtolength{\boxwidth}{-8\FrameSep}
  \addtolength{\boxwidth}{-2\FrameRule}
  \setlength{\hsize}{\boxwidth} \FrameRestore}}%%
{\endMakeFramed}

\makeatletter
\renewenvironment{notice}[2]{
  \begin{samepage}
  \begin{NoticeBox}
  \def\py@noticetypetip{tip}
  \def\py@noticetypenote{note}
  \def\py@noticetype{#1}

  \setlength\tabcolsep{1mm}
  \renewcommand{\arraystretch}{0.3}
  \begin{tabular}[t]{cp{%(notice_width)s}}
    \ifx\py@noticetype\py@noticetypetip
      %% TIPS:
      \hspace{-5mm}
      \scalebox{0.5}{\includegraphics{tip.png}}
    \else
      %% NOTES:
      \hspace{-2mm}
      \scalebox{0.8}{\includegraphics{note.png}}
      \hspace{1mm}
    \fi
    &
    \ifx\py@noticetype\py@noticetypetip
      %% TIPS:
      \vspace{-3.2\baselineskip}
    \else
      %% NOTES:
      \vspace{-2.8\baselineskip}
    \fi
    \setlength{\parskip}{2mm}
}
{
  \end{tabular}
  \end{NoticeBox}
  \end{samepage}
}
\makeatother
%% float variables:
\renewcommand{\topfraction}{0.9} %% max fraction of floats at top
\renewcommand{\bottomfraction}{0.8} %% max fraction of floats at bottom
%%   Parameters for TEXT pages (not float pages):
\setcounter{topnumber}{2}
\setcounter{bottomnumber}{2}
\setcounter{totalnumber}{4}     %% 2 may work better
\setcounter{dbltopnumber}{2}    %% for 2-column pages
\renewcommand{\dbltopfraction}{0.9} %% fit big float above 2-col. text
\renewcommand{\textfraction}{0.07} %% allow minimal text w. figs
%%   Parameters for FLOAT pages (not text pages):
\renewcommand{\floatpagefraction}{0.7} %% require fuller float pages
%% N.B.: floatpagefraction MUST be less than topfraction !!
\renewcommand{\dblfloatpagefraction}{0.7} %% require fuller float pages
%% END of float variables.
""" % chosen_format

latex_elements = {
    'preamble': tiny_latex_include,
}

def end_foreword_directive(name, arguments, options, content, lineno,
                       content_offset, block_text, state, state_machine):
    return [nodes.Text('SPHINXENDFOREWORDDIRECTIVE\n')]

def begin_conclusion_directive(name, arguments, options, content, lineno,
                       content_offset, block_text, state, state_machine):
    return [nodes.Text('SPHINXBEGINCONCLUSIONDIRECTIVE\n')]

def setup(app):
    app.add_directive('end_foreword', end_foreword_directive, 1, (0, 0, 0))
    app.add_directive('begin_conclusion', begin_conclusion_directive, 1, (0, 0, 0))

